gravity:
  version: v1
  address: localhost:8004
  sdb:
      - http://0.0.0.0:8200
  db:
      - 0.0.0.0:2379
  flusher: 0.0.0.0:4222
  instrument:
    address: 0.0.0.0:4222
    stopic: collector
    collect: 15s
    location: logs/
